name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  do-thing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Verify running from tag
        uses: actions/github-script@v6
        if: github.ref_type != 'tag'
        with:
          script: |
              core.setFailed("This workflow must be run from a tag")

      - name: Get version from tag
        id: get-version
        uses: actions/github-script@v6
        with:
          script: |
              const tag = context.ref.replace("refs/tags/", "");
              const rcPattern = /v\d+\.\d+\.\d+rc\d+/;
              if (!rcPattern.test(tag)) {
                core.setFailed("This workflow must be run on a release candidate tag ref, e.g v1.0.0rc01");
                return;
              }
              const versionWithoutRc = tag.replace(/rc\d+/, "");
              return versionWithoutRc;
          result-encoding: string
          
      - name: Print version
        run: echo ${{ steps.get-version.outputs.result }}
              
              
