name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  do-thing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get version from tag
        id: get-version
        uses: actions/github-script@v6
        with:
          script: |
              const rcPattern = /v\d+\.\d+\.\d+rc\d+/
              console.log(github.ref_type);
              console.log(github.ref_name);
              console.log(github.ref_type !== "tag");
              console.log(!rcPattern.test(github.ref_name));
              if (github.ref_type !== "tag" || !rcPattern.test(github.ref_name)) {
                core.setFailed("This workflow must be run on a release candidate tag ref, e.g v1.0.0rc01");
                return;
              }
              const versionWithoutRc = github.ref_name.replace(/rc\d+/, "");
              return versionWithoutRc;
          result-encoding: string
          
      - name: Print version
        run: echo ${{ steps.get-version.outputs.result }}
              
              
